### ISSUE TITLE
Is it possible to set return type to slice of pointers

### ISSUE THREAD

**Issue by miniscruff** [opendoor/pggen#185]
I have a query shim that is effectively: 
```toml
[[query]]
	name = "GetAllX"
	return_type = "[]*X"
	body = '''
	SELECT * FROM xs;
	'''
```

However when the function is generated it looks like:
```go
GetAllX(ctx context.Context, ([]X, error)
```

If possible I would prefer it to be: 
```go
GetAllX(ctx context.Context, ([]*X, error)
```

Ideally all the ListX operations would return `[]*X` as well, maybe an option not sure.

Note: Willing to try my hand at contributing if that would help.
